# Generated by Django 3.1.7 on 2021-03-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='', max_length=20, verbose_name='ユーザID'),
        ),
    ]
