# Generated by Django 3.1.7 on 2021-03-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='', max_length=20, verbose_name='ユーザーID'),
        ),
    ]
