# Generated by Django 3.1.7 on 2021-04-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_user_youtube_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channelid', models.CharField(max_length=100, unique=True, verbose_name='チャンネルID')),
                ('title', models.CharField(max_length=100, verbose_name='チャンネルタイトル')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('subscriberCount', models.IntegerField(verbose_name='登録者数')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='youtube_id',
        ),
        migrations.AddField(
            model_name='user',
            name='yt_channels',
            field=models.ManyToManyField(blank=True, related_name='yt_channels', to='testapp.YoutubeChannel'),
        ),
        migrations.AddField(
            model_name='user',
            name='yt_subscriptions',
            field=models.ManyToManyField(blank=True, related_name='yt_subscriptions', to='testapp.YoutubeChannel'),
        ),
    ]
